### ISSUE TITLE
本次交易未提供任何付款方式，請與商店聯繫確認。

### ISSUE THREAD

**Issue by linsamtw** [ECPay/ECPayAIO_Python#4]
# 本次交易未提供任何付款方式，請與商店聯繫確認。
為啥本來可以收款的交易連結，現在通通顯示

本次交易未提供任何付款方式，請與商店聯繫確認。

不論是我串接你們家的 api，還是收款連結，通通失效

你們不是說 8/1 才會開始修改方案嗎?

7/1~7/31 都可以補件，現在是?????

**Comment by adelachang0418** [comment]
您好，補件相關問題請洽負責業務或是客服人員
如果有其他相關的串接技術問題，再麻煩提供更詳盡的說明以便釐清問題
謝謝您
